namespace AslLabApi.Migrations
{
    using System;
    using System.Data.Entity.Migrations;
    
    public partial class InitialCreate2 : DbMigration
    {
        public override void Up()
        {
            AddColumn("dbo.HMS_DEPT", "USERPC", c => c.String());
            AddColumn("dbo.HMS_DEPT", "INSUSERID", c => c.Long());
            AddColumn("dbo.HMS_DEPT", "INSTIME", c => c.DateTime());
            AddColumn("dbo.HMS_DEPT", "INSIPNO", c => c.String());
            AddColumn("dbo.HMS_DEPT", "INSLTUDE", c => c.String());
            AddColumn("dbo.HMS_DEPT", "UPDUSERID", c => c.Long());
            AddColumn("dbo.HMS_DEPT", "UPDTIME", c => c.DateTime());
            AddColumn("dbo.HMS_DEPT", "UPDIPNO", c => c.String());
            AddColumn("dbo.HMS_DEPT", "UPDLTUDE", c => c.String());
            AddColumn("dbo.HMS_MGT", "USERPC", c => c.String());
            AddColumn("dbo.HMS_MGT", "INSUSERID", c => c.Long());
            AddColumn("dbo.HMS_MGT", "INSTIME", c => c.DateTime());
            AddColumn("dbo.HMS_MGT", "INSIPNO", c => c.String());
            AddColumn("dbo.HMS_MGT", "INSLTUDE", c => c.String());
            AddColumn("dbo.HMS_MGT", "UPDUSERID", c => c.Long());
            AddColumn("dbo.HMS_MGT", "UPDTIME", c => c.DateTime());
            AddColumn("dbo.HMS_MGT", "UPDIPNO", c => c.String());
            AddColumn("dbo.HMS_MGT", "UPDLTUDE", c => c.String());
            AddColumn("dbo.HMS_MGTRF", "USERPC", c => c.String());
            AddColumn("dbo.HMS_MGTRF", "INSUSERID", c => c.Long());
            AddColumn("dbo.HMS_MGTRF", "INSTIME", c => c.DateTime());
            AddColumn("dbo.HMS_MGTRF", "INSIPNO", c => c.String());
            AddColumn("dbo.HMS_MGTRF", "INSLTUDE", c => c.String());
            AddColumn("dbo.HMS_MGTRF", "UPDUSERID", c => c.Long());
            AddColumn("dbo.HMS_MGTRF", "UPDTIME", c => c.DateTime());
            AddColumn("dbo.HMS_MGTRF", "UPDIPNO", c => c.String());
            AddColumn("dbo.HMS_MGTRF", "UPDLTUDE", c => c.String());
            AddColumn("dbo.HMS_REFER", "USERPC", c => c.String());
            AddColumn("dbo.HMS_REFER", "INSUSERID", c => c.Long());
            AddColumn("dbo.HMS_REFER", "INSTIME", c => c.DateTime());
            AddColumn("dbo.HMS_REFER", "INSIPNO", c => c.String());
            AddColumn("dbo.HMS_REFER", "INSLTUDE", c => c.String());
            AddColumn("dbo.HMS_REFER", "UPDUSERID", c => c.Long());
            AddColumn("dbo.HMS_REFER", "UPDTIME", c => c.DateTime());
            AddColumn("dbo.HMS_REFER", "UPDIPNO", c => c.String());
            AddColumn("dbo.HMS_REFER", "UPDLTUDE", c => c.String());
            AddColumn("dbo.HMS_RFPCNT", "USERPC", c => c.String());
            AddColumn("dbo.HMS_RFPCNT", "INSUSERID", c => c.Long());
            AddColumn("dbo.HMS_RFPCNT", "INSTIME", c => c.DateTime());
            AddColumn("dbo.HMS_RFPCNT", "INSIPNO", c => c.String());
            AddColumn("dbo.HMS_RFPCNT", "INSLTUDE", c => c.String());
            AddColumn("dbo.HMS_RFPCNT", "UPDUSERID", c => c.Long());
            AddColumn("dbo.HMS_RFPCNT", "UPDTIME", c => c.DateTime());
            AddColumn("dbo.HMS_RFPCNT", "UPDIPNO", c => c.String());
            AddColumn("dbo.HMS_RFPCNT", "UPDLTUDE", c => c.String());
            AddColumn("dbo.HMS_SIGNBY", "USERPC", c => c.String());
            AddColumn("dbo.HMS_SIGNBY", "INSUSERID", c => c.Long());
            AddColumn("dbo.HMS_SIGNBY", "INSTIME", c => c.DateTime());
            AddColumn("dbo.HMS_SIGNBY", "INSIPNO", c => c.String());
            AddColumn("dbo.HMS_SIGNBY", "INSLTUDE", c => c.String());
            AddColumn("dbo.HMS_SIGNBY", "UPDUSERID", c => c.Long());
            AddColumn("dbo.HMS_SIGNBY", "UPDTIME", c => c.DateTime());
            AddColumn("dbo.HMS_SIGNBY", "UPDIPNO", c => c.String());
            AddColumn("dbo.HMS_SIGNBY", "UPDLTUDE", c => c.String());
            AddColumn("dbo.HMS_TEST", "USERPC", c => c.String());
            AddColumn("dbo.HMS_TEST", "INSUSERID", c => c.Long());
            AddColumn("dbo.HMS_TEST", "INSTIME", c => c.DateTime());
            AddColumn("dbo.HMS_TEST", "INSIPNO", c => c.String());
            AddColumn("dbo.HMS_TEST", "INSLTUDE", c => c.String());
            AddColumn("dbo.HMS_TEST", "UPDUSERID", c => c.Long());
            AddColumn("dbo.HMS_TEST", "UPDTIME", c => c.DateTime());
            AddColumn("dbo.HMS_TEST", "UPDIPNO", c => c.String());
            AddColumn("dbo.HMS_TEST", "UPDLTUDE", c => c.String());
            AddColumn("dbo.HMS_TESTMST", "USERPC", c => c.String());
            AddColumn("dbo.HMS_TESTMST", "INSUSERID", c => c.Long());
            AddColumn("dbo.HMS_TESTMST", "INSTIME", c => c.DateTime());
            AddColumn("dbo.HMS_TESTMST", "INSIPNO", c => c.String());
            AddColumn("dbo.HMS_TESTMST", "INSLTUDE", c => c.String());
            AddColumn("dbo.HMS_TESTMST", "UPDUSERID", c => c.Long());
            AddColumn("dbo.HMS_TESTMST", "UPDTIME", c => c.DateTime());
            AddColumn("dbo.HMS_TESTMST", "UPDIPNO", c => c.String());
            AddColumn("dbo.HMS_TESTMST", "UPDLTUDE", c => c.String());
            AddColumn("dbo.HMS_TESTNV", "USERPC", c => c.String());
            AddColumn("dbo.HMS_TESTNV", "INSUSERID", c => c.Long());
            AddColumn("dbo.HMS_TESTNV", "INSTIME", c => c.DateTime());
            AddColumn("dbo.HMS_TESTNV", "INSIPNO", c => c.String());
            AddColumn("dbo.HMS_TESTNV", "INSLTUDE", c => c.String());
            AddColumn("dbo.HMS_TESTNV", "UPDUSERID", c => c.Long());
            AddColumn("dbo.HMS_TESTNV", "UPDTIME", c => c.DateTime());
            AddColumn("dbo.HMS_TESTNV", "UPDIPNO", c => c.String());
            AddColumn("dbo.HMS_TESTNV", "UPDLTUDE", c => c.String());
            AddColumn("dbo.HMS_TESTV", "USERPC", c => c.String());
            AddColumn("dbo.HMS_TESTV", "INSUSERID", c => c.Long());
            AddColumn("dbo.HMS_TESTV", "INSTIME", c => c.DateTime());
            AddColumn("dbo.HMS_TESTV", "INSIPNO", c => c.String());
            AddColumn("dbo.HMS_TESTV", "INSLTUDE", c => c.String());
            AddColumn("dbo.HMS_TESTV", "UPDUSERID", c => c.Long());
            AddColumn("dbo.HMS_TESTV", "UPDTIME", c => c.DateTime());
            AddColumn("dbo.HMS_TESTV", "UPDIPNO", c => c.String());
            AddColumn("dbo.HMS_TESTV", "UPDLTUDE", c => c.String());
        }
        
        public override void Down()
        {
            DropColumn("dbo.HMS_TESTV", "UPDLTUDE");
            DropColumn("dbo.HMS_TESTV", "UPDIPNO");
            DropColumn("dbo.HMS_TESTV", "UPDTIME");
            DropColumn("dbo.HMS_TESTV", "UPDUSERID");
            DropColumn("dbo.HMS_TESTV", "INSLTUDE");
            DropColumn("dbo.HMS_TESTV", "INSIPNO");
            DropColumn("dbo.HMS_TESTV", "INSTIME");
            DropColumn("dbo.HMS_TESTV", "INSUSERID");
            DropColumn("dbo.HMS_TESTV", "USERPC");
            DropColumn("dbo.HMS_TESTNV", "UPDLTUDE");
            DropColumn("dbo.HMS_TESTNV", "UPDIPNO");
            DropColumn("dbo.HMS_TESTNV", "UPDTIME");
            DropColumn("dbo.HMS_TESTNV", "UPDUSERID");
            DropColumn("dbo.HMS_TESTNV", "INSLTUDE");
            DropColumn("dbo.HMS_TESTNV", "INSIPNO");
            DropColumn("dbo.HMS_TESTNV", "INSTIME");
            DropColumn("dbo.HMS_TESTNV", "INSUSERID");
            DropColumn("dbo.HMS_TESTNV", "USERPC");
            DropColumn("dbo.HMS_TESTMST", "UPDLTUDE");
            DropColumn("dbo.HMS_TESTMST", "UPDIPNO");
            DropColumn("dbo.HMS_TESTMST", "UPDTIME");
            DropColumn("dbo.HMS_TESTMST", "UPDUSERID");
            DropColumn("dbo.HMS_TESTMST", "INSLTUDE");
            DropColumn("dbo.HMS_TESTMST", "INSIPNO");
            DropColumn("dbo.HMS_TESTMST", "INSTIME");
            DropColumn("dbo.HMS_TESTMST", "INSUSERID");
            DropColumn("dbo.HMS_TESTMST", "USERPC");
            DropColumn("dbo.HMS_TEST", "UPDLTUDE");
            DropColumn("dbo.HMS_TEST", "UPDIPNO");
            DropColumn("dbo.HMS_TEST", "UPDTIME");
            DropColumn("dbo.HMS_TEST", "UPDUSERID");
            DropColumn("dbo.HMS_TEST", "INSLTUDE");
            DropColumn("dbo.HMS_TEST", "INSIPNO");
            DropColumn("dbo.HMS_TEST", "INSTIME");
            DropColumn("dbo.HMS_TEST", "INSUSERID");
            DropColumn("dbo.HMS_TEST", "USERPC");
            DropColumn("dbo.HMS_SIGNBY", "UPDLTUDE");
            DropColumn("dbo.HMS_SIGNBY", "UPDIPNO");
            DropColumn("dbo.HMS_SIGNBY", "UPDTIME");
            DropColumn("dbo.HMS_SIGNBY", "UPDUSERID");
            DropColumn("dbo.HMS_SIGNBY", "INSLTUDE");
            DropColumn("dbo.HMS_SIGNBY", "INSIPNO");
            DropColumn("dbo.HMS_SIGNBY", "INSTIME");
            DropColumn("dbo.HMS_SIGNBY", "INSUSERID");
            DropColumn("dbo.HMS_SIGNBY", "USERPC");
            DropColumn("dbo.HMS_RFPCNT", "UPDLTUDE");
            DropColumn("dbo.HMS_RFPCNT", "UPDIPNO");
            DropColumn("dbo.HMS_RFPCNT", "UPDTIME");
            DropColumn("dbo.HMS_RFPCNT", "UPDUSERID");
            DropColumn("dbo.HMS_RFPCNT", "INSLTUDE");
            DropColumn("dbo.HMS_RFPCNT", "INSIPNO");
            DropColumn("dbo.HMS_RFPCNT", "INSTIME");
            DropColumn("dbo.HMS_RFPCNT", "INSUSERID");
            DropColumn("dbo.HMS_RFPCNT", "USERPC");
            DropColumn("dbo.HMS_REFER", "UPDLTUDE");
            DropColumn("dbo.HMS_REFER", "UPDIPNO");
            DropColumn("dbo.HMS_REFER", "UPDTIME");
            DropColumn("dbo.HMS_REFER", "UPDUSERID");
            DropColumn("dbo.HMS_REFER", "INSLTUDE");
            DropColumn("dbo.HMS_REFER", "INSIPNO");
            DropColumn("dbo.HMS_REFER", "INSTIME");
            DropColumn("dbo.HMS_REFER", "INSUSERID");
            DropColumn("dbo.HMS_REFER", "USERPC");
            DropColumn("dbo.HMS_MGTRF", "UPDLTUDE");
            DropColumn("dbo.HMS_MGTRF", "UPDIPNO");
            DropColumn("dbo.HMS_MGTRF", "UPDTIME");
            DropColumn("dbo.HMS_MGTRF", "UPDUSERID");
            DropColumn("dbo.HMS_MGTRF", "INSLTUDE");
            DropColumn("dbo.HMS_MGTRF", "INSIPNO");
            DropColumn("dbo.HMS_MGTRF", "INSTIME");
            DropColumn("dbo.HMS_MGTRF", "INSUSERID");
            DropColumn("dbo.HMS_MGTRF", "USERPC");
            DropColumn("dbo.HMS_MGT", "UPDLTUDE");
            DropColumn("dbo.HMS_MGT", "UPDIPNO");
            DropColumn("dbo.HMS_MGT", "UPDTIME");
            DropColumn("dbo.HMS_MGT", "UPDUSERID");
            DropColumn("dbo.HMS_MGT", "INSLTUDE");
            DropColumn("dbo.HMS_MGT", "INSIPNO");
            DropColumn("dbo.HMS_MGT", "INSTIME");
            DropColumn("dbo.HMS_MGT", "INSUSERID");
            DropColumn("dbo.HMS_MGT", "USERPC");
            DropColumn("dbo.HMS_DEPT", "UPDLTUDE");
            DropColumn("dbo.HMS_DEPT", "UPDIPNO");
            DropColumn("dbo.HMS_DEPT", "UPDTIME");
            DropColumn("dbo.HMS_DEPT", "UPDUSERID");
            DropColumn("dbo.HMS_DEPT", "INSLTUDE");
            DropColumn("dbo.HMS_DEPT", "INSIPNO");
            DropColumn("dbo.HMS_DEPT", "INSTIME");
            DropColumn("dbo.HMS_DEPT", "INSUSERID");
            DropColumn("dbo.HMS_DEPT", "USERPC");
        }
    }
}
